version: "3.8"

services:
  postgres:
    container_name: cubos_academy_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cubos_academy
